<?php
//cms配置变量
$article_diggPower=1;
$webTitle="iwebsns平台cms插件-聚易技术团队首款多功能信息聚合模块";
$webDesc="插件，cms";
$webKeys="iwebsns,cms,jooyea";
$webAuthor="jooyea";
$tplName="default";
$comType=2;
$diggType=2;
$compType="server";
?>